### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by jonhue** [mrchntia/hello-world#1]
Great job on setting up this project, @mrchntia!

The readme and contributing guide are very welcoming and well structured.

That said, one thing that I find repositories benefit greatly from is issue and pull request templates. They would allow you to nudge potential contributors in the right direction when reporting a bug, requesting a feature, or proposing a pull request. Meaning that contributors can be more certain of what they are expected to deliver while you can be assured that you will need to use less time to ask contributors for further details. 🙂 

Here is a link to the corresponding GitHub docs: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests.

That is just a very minor nitpick though. Overall, great work on this!

**Comment by mrchntia** [comment]
Thanks a lot for the feedback, @jonhue .

I am happy that you reminded me of the great github feature for issue and pull request templates. They are now added to this project.
